### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by renatamuy** [NINAnor/oneimpact#9]
Ber, 

Estou usando `grassdir <- "C:/Program Files/GRASS GIS 7.8"`, talvez comentar nos exemplos para usuários de Windows?

Tentei rodar o [exemplo](https://github.com/renatamuy/oneimpact/blob/main/examples/calc_zoi_cumulative_grass_example.R). O script criou a db de boa e importou o raster normalmente, mas deu erro na linha 38 do exemplo, na hora de criar `cabins_bin_g` usando `grass_binarize()`:

`Error in system(cmd0, intern = TRUE) : 'r.mapcalc.simple.exe' not found
Error in parseGRASS(cmd, legacyExec = legacyExec) : 
  r.mapcalc.simple not found`

**Comment by bniebuhr** [comment]
Oi Re.
Nao consegui reproduzir o seu exemplo. Mas por hora comecei a documentar algumas formas de rodar as metricas em Windows no issue #10 .
Tem pelo menos mais uma forma que eu quero tentar - abrindo o GRASS e rodando o R a partir do console.

**Comment by bniebuhr** [comment]
Closing that for now.
